apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - name: argocd-app
          image: argocd-app:latest
          ports:
            - containerPort: 8080
